import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.android.application")
}

// ---- Version / GitHub repo (CI passes -PversionName -PversionCode -PgithubRepo) ----
fun String.cleanVersion(): String =
    removePrefix("v").substringBefore("-").trim().ifBlank { "1.0.0" }

val versionNameProp: String =
    (findProperty("versionName") as String?)?.cleanVersion()
        ?: (findProperty("VERSION_NAME") as String?)?.cleanVersion()
        ?: "1.0.0"

val versionCodeProp: Int =
    (findProperty("versionCode") as String?)?.toIntOrNull()
        ?: versionNameProp.substringAfterLast('.').filter { it.isDigit() }.toIntOrNull()
        ?: 1

val githubRepoProp: String =
    (findProperty("githubRepo") as String?)
        ?: System.getenv("GITHUB_REPOSITORY")
        ?: (findProperty("GITHUB_REPO") as String?)
        ?: ""

val generateDesktopVersion by tasks.registering {
    val outFile = layout.projectDirectory
        .file("src/desktopMain/kotlin/com/quickgerrit/app/platform/GeneratedVersion.kt")
        .asFile
    inputs.property("versionName", versionNameProp)
    inputs.property("versionCode", versionCodeProp)
    inputs.property("githubRepo", githubRepoProp)
    outputs.file(outFile)
    doLast {
        outFile.parentFile.mkdirs()
        // Escape for Kotlin string
        val repoEscaped = githubRepoProp.replace("\\", "\\\\").replace("\"", "\\\"")
        outFile.writeText(
            """
            package com.quickgerrit.app.platform

            /** AUTO-GENERATED by Gradle generateDesktopVersion — do not edit. */
            object GeneratedVersion {
                const val VERSION_NAME: String = "$versionNameProp"
                const val VERSION_CODE: Int = $versionCodeProp
                const val GITHUB_REPO: String = "$repoEscaped"
            }
            """.trimIndent() + "\n"
        )
        logger.lifecycle(
            "GeneratedVersion → VERSION_NAME=$versionNameProp VERSION_CODE=$versionCodeProp GITHUB_REPO=${githubRepoProp.ifBlank { "(empty)" }}"
        )
    }
}

// Ensure every desktop compile regenerates version constants
tasks.matching {
    val n = it.name
    n.contains("compileKotlinDesktop", ignoreCase = true) ||
        n.contains("compileDesktopMain", ignoreCase = true) ||
        n.startsWith("desktop") && n.contains("Kotlin", ignoreCase = true)
}.configureEach {
    dependsOn(generateDesktopVersion)
}

// Also before packaging / run
tasks.matching {
    it.name in setOf(
        "run", "runRelease", "createDistributable", "packageDeb", "packageRpm",
        "packageAppImage", "packageMsi", "packageDistributionForCurrentOS"
    ) || it.name.startsWith("package")
}.configureEach {
    dependsOn(generateDesktopVersion)
}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "17"
            }
        }
    }

    jvm("desktop")

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(compose.components.uiToolingPreview)

                implementation("com.squareup.okhttp3:okhttp:4.12.0")
                implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
                implementation("com.squareup.retrofit2:retrofit:2.11.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
                implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

                implementation("com.russhwolf:multiplatform-settings:1.2.0")
                implementation("com.russhwolf:multiplatform-settings-coroutines:1.2.0")
                implementation("com.russhwolf:multiplatform-settings-serialization:1.2.0")
            }
        }
        val androidMain by getting {
            dependencies {
                implementation("androidx.activity:activity-compose:1.9.3")
                implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
                implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
                implementation("androidx.navigation:navigation-compose:2.8.4")
                implementation("androidx.datastore:datastore-preferences:1.1.1")
                implementation("io.coil-kt:coil-compose:2.7.0")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")
            }
        }
        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0")
            }
        }
    }
}

android {
    namespace = "com.quickgerrit.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.quickgerrit.app"
        minSdk = 26
        targetSdk = 35
        versionCode = versionCodeProp
        versionName = versionNameProp
        buildConfigField("String", "GITHUB_REPO", "\"${githubRepoProp.replace("\"", "\\\"")}\"")
        buildConfigField("String", "UPDATE_APK_NAME", "\"QuickGerrit-debug.apk\"")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.quickgerrit.app.MainKt"

        jvmArgs += listOf(
            "-Dquickgerrit.version=$versionNameProp",
            "-Dquickgerrit.versionCode=$versionCodeProp",
            "-Dquickgerrit.githubRepo=$githubRepoProp"
        )

        nativeDistributions {
            targetFormats(
                TargetFormat.Dmg,
                TargetFormat.Msi,
                TargetFormat.Deb,
                TargetFormat.Rpm,
                TargetFormat.AppImage
            )
            packageName = "QuickGerrit"
            packageVersion = if (versionNameProp.matches(Regex("""\d+\.\d+\.\d+"""))) {
                versionNameProp
            } else {
                "1.0.0"
            }
            description = "Modern Gerrit Code Review client"
            copyright = "© 2026 QuickGerrit"
            vendor = "QuickGerrit"

            windows {
                menuGroup = "QuickGerrit"
            }
            linux {
            }
            macOS {
                bundleID = "com.quickgerrit.app"
            }
        }
    }
}
