package com.quickgerrit.app.platform

/**
 * AUTO-GENERATED by Gradle task `generateDesktopVersion`.
 * Do not edit by hand — values are replaced on every desktop build.
 */
object GeneratedVersion {
    const val VERSION_NAME: String = "0.0.0"
    const val VERSION_CODE: Int = 0
    const val GITHUB_REPO: String = ""
}
