package com.quickgerrit.app.platform

/**
 * AUTO-GENERATED by Gradle task `generateDesktopVersion`.
 * Replaced on every desktop build when -PversionName / -PgithubRepo are passed.
 */
object GeneratedVersion {
    const val VERSION_NAME: String = "0.0.0"
    const val VERSION_CODE: Int = 0
    const val GITHUB_REPO: String = ""
}
